source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'mongoid'
gem 'devise'

gem 'locomotivecms_common', github: 'locomotivecms/common', ref: 'c2a1c48c326e947bca2c6f56dacda8a7c8f3930a'
gem 'custom_fields', github: 'locomotivecms/custom_fields', ref: '251b1b93472506f5eb255d60d92f65bcfc354095'
gem 'locomotivecms_steam', github: 'locomotivecms/steam', ref: '77fa10c6156da36c423065dcdb22c42e595b70df'
gem 'locomotivecms', github: 'acsone/engine', ref: '2c85b593c302e783038d79152fc536836c68e0a4'
gem 'shop_invader', github: 'shopinvader/locomotive-shopinvader', branch: 'v4.0.x'
gem 'mongo_session_store', '~> 3.1.0'

# TODO FIXME needed to precompile asset in docker
gem 'listen', '>= 3.0.5', '< 3.2'
gem 'nokogiri', '>= 1.10.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use Puma as the app server
gem 'puma', '~> 3.11'
gem 'puma_worker_killer'
# gem 'passenger-rails'
gem 'rack-cors', require: 'rack/cors'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'carrierwave-aws'

# gem 'sidekiq'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

group :production do
  gem "sentry-raven"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
